### PR TITLE
fix: Change location of api spec and remove fields from App

### PR DESCRIPTION
**Pull request by davidffrench**
## Motivation
No JIRA

## What
Change the location of api spec and removing disabled and disabledMessage fields from App level

## Why
Adhering to Go folder structure by moving swagger spec file to api folder. 
Removing disabled and disabledMessage fields due to change in UI.

## Verification Steps
Not possible to verify the changes until they are in GitHub :-(

### CODE REVIEW

**Comment by davidffrench** [comment]
> Commit message isn't adhering to our new standard:
> 
> `fix(scope): Change location of api spec and remove fields from App (AEROGEAR-XXXX)`

I have found the first problem with the commit message format. If there is no JIRA associated. @laurafitzgerald What is your opinion on always having a JIRA for every change?

**Comment by craicoverflow** [comment]
> > Commit message isn't adhering to our new standard:
> > `fix(scope): Change location of api spec and remove fields from App (AEROGEAR-XXXX)`
> 
> I have found the first problem with the commit message format. If there is no JIRA associated. @laurafitzgerald What is your opinion on always having a JIRA for every change?

This is also relevant to @austincunningham as he is working on the CircleCI regex rule for this.

**Comment by austincunningham** [comment]
(AEROGEAR-XXXX) will satisfy the rule at present

**Comment by davidffrench** [comment]
Modified now. I change it to (none) first but I didn't like it that way.

**Pull request merged**
