### PR TITLE
feat(handler-unit-tests) : Create mock file for the handler and it unit tests (AEROGEAR-8558)

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
https://issues.jboss.org/browse/AEROGEAR-8558

## What
After the AEROGEAR-8557 then mock the handler and create unit tests to cover it

## Why
- Add unit test 
- Use assert 

## How
- Create a mock
- Add unit test
- refactoring service test to use asserts as it is the echo framework doc. See [here](https://echo.labstack.com/guide/testing)

## Verification Steps
- Check if the CI still working with success
 
## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress
- [X ] Finished task

## Additional Notes
Ps.: I take the advantage to fix the unit test of the service here.

### CODE REVIEW

**Comment by austincunningham** [comment]
Doesn't appear to be effecting the coverage for the handler https://coveralls.io/builds/21785387/source?filename=pkg/web/apps/apps_http_handler.go, I'm having this issue as well with the service

**Comment by austincunningham** [comment]
Looks like it never hits the handler it only hits the mock of the handler

**Comment by camilamacedo86** [comment]
@austincunningham 

Regards:

`Doesn't appear to be effecting the coverage for the handler https://coveralls.io/builds/21785387/source?filename=pkg/web/apps/apps_http_handler.go, I'm having this issue as well with the service`

it is because of: 

The `Coverage decreased (-1.2%) to 67.677%` because the cover is counting the files which shouldn't. 
The PR https://github.com/aerogear/mobile-security-service/pull/65 and the PR https://github.com/aerogear/mobile-security-service/pull/67 has the propose to solve these points. 

I am rebasing this with the master and we will check it.

**Comment by austincunningham** [comment]
your rebase didn't fix the issue handlers file is still not hit by coveralls and tests https://coveralls.io/builds/21786407/source?filename=pkg/web/apps/apps_http_handler.go

**Comment by camilamacedo86** [comment]
@austincunningham it shows doing the same checks that we can find in the echo API see [here](https://echo.labstack.com/guide/testing).

**Comment by camilamacedo86** [comment]
@austincunningham Issue solved !!! I will create another PR to fix the service one since it requires mock the database.

**Pull request merged**
