### PR TITLE
Aerogear 8454

### PR DESCRIPTION
**Pull request by davidffrench**
## Motivation
https://issues.jboss.org/browse/AEROGEAR-8454
Broken links on Readme

## What
Link to contributing and code of conduct are broken in both prerequisites section and contributing section of our Readme

## How
Contributing and Questions section now links to contact section on the aerogear site.

## Verification Steps
1. Verify license badge is showing on Readme
2. Click contributing guide and verify it links to aerogear community guides 
3. Click AeroGear community and verify it links to aerogear community contact

### CODE REVIEW

**Comment by austincunningham** [comment]
not in this pr but the first contributing link is dead in the doc

**Comment by laurafitzgerald** [comment]
@austincunningham nicely spotted. I think I mentioned it in the JIRA. It's a small one so probably makes sense to complete here?

**Comment by damienomurchu** [comment]
@austincunningham @laurafitzgerald .github/CONTRIBUTING.MD will still populate a link when a user opens an issue/ PR as per [here](https://github.blog/2012-09-17-contributing-guidelines/). If we're redirecting to Aerogear.org which will have the most up to date contributing information perhaps we no longer want this file in the repo?

**Comment by davidffrench** [comment]
@austincunningham Just to confirm, are you talking about the contributing link that is fixed in this PR?

**Comment by austincunningham** [comment]
no is one at the top of  the doc

**Comment by davidffrench** [comment]
thanks @austincunningham . Fixed now

**Pull request merged**
